spring:
  output.ansi.enabled: DETECT
  session.store-type: none
  cache:
    cache-names: dc-models
    caffeine.spec: maximumSize=200,expireAfterAccess=3600s
    type: caffeine

server:
  compression.enabled: true

# URI is of the form mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
spring.data.mongodb.uri: mongodb://localhost/dcexporter

application:
  url: http://localhost:3000
  security:
    fetchUserInfo: true
  syncDelay: 10000
  syncDatasetUrl: 3600000

# TODO : Copied pasted from portal configuration, check if we really need all of them
kernel:
  base_uri: https://kernel.ozwillo-preprod.eu
  account_uri: https://accounts.ozwillo-preprod.eu
  alt_uri: ${kernel.base_uri}
  auth:
    issuer: ${kernel.base_uri}/
    auth_endpoint: ${kernel.alt_uri}/a/auth
    token_endpoint: ${kernel.base_uri}/a/token
    keys_endpoint: ${kernel.base_uri}/a/keys
    userinfo_endpoint: ${kernel.base_uri}/a/userinfo
    password_change_endpoint: ${kernel.alt_uri}/a/password
    revoke_endpoint: ${kernel.base_uri}/a/revoke
    logout_endpoint: ${kernel.alt_uri}/a/logout
    callback_uri: ${application.url}/callback
    home_uri: ${application.url}
  account_france_connect_uri: ${kernel.account_uri}/a/franceconnect
  kernel_france_connect_uri: ${kernel.base_uri}/a/franceconnect
  france_connect:
    link_endpoint: ${kernel.account_france_connect_uri}/login
    unlink_endpoint: ${kernel.account_france_connect_uri}/unlink
    userinfo_endpoint: ${kernel.kernel_france_connect_uri}/userinfo
  user_profile_endpoint: ${kernel.base_uri}/d/user
  user_membership_endpoint: ${kernel.base_uri}/d
  organization_endpoint: ${kernel.base_uri}/d/org
  event_bus_endpoint: ${kernel.base_uri}/e
  notifications_endpoint: ${kernel.base_uri}/n
  client_id: portal
  client_secret: secret
  # NB. once Datacore cache is in place, move datacore scope to its dedicated system user
  scopes_to_require: openid profile email address phone datacore

datacore:
  #url: http://localhost:8080
  containerUrl: http://data.ozwillo.com
  #url: https://data.ozwillo-dev.eu    # dev, doesn't work with current gen'd cert
  url: https://data.ozwillo-preprod.eu             # dev, requires (MUST) set the IP in /etc/hosts, and installing gen'd cert :
  # go to https://data.ozwillo-dev.eu, right click on lock, export certificate to plnm-dev-dc.cer,
  # then import it and check :
  # sudo keytool -import -alias plnm-dev-dc -keystore /usr/lib/jvm/jdk1.8.xx/jre/lib/security/cacerts -file plnm-dev-dc.cer
  # keytool -list -v -keystore /usr/lib/jvm/jdk1.8.xx/jre/lib/security/cacerts
  # On recent Mac OS, cacerts is in /Library/Java/JavaVirtualMachines/jdk1.8.0_XX.jdk/Contents/Home/jre/lib/security
  # (or execute /usr/libexec/java_home to find where Java is installed on your MacOS system)
  systemAdminUser:  # Get it using Node.js lib / with portal clientId
    refreshToken: refreshToken
    nonce: changeit      #Set it when getting the refreshToken
  modifiedField: "dc:modified"
  # maximum number of resources we allow to export for a given model
  # this is to avoid huge datasets that are not suited to be exposed on an Open Data platform
  maxSynchronizedResourcesPerModel: 10000

ckan:
  url: https://opendata.ozwillo.com
  apikey: your-ckan-api-key

geocoding:
  url: http://api-adresse.data.gouv.fr